**1- Importing Packages**

In [1]:
import numpy as np
print(np.__version__)

2.4.3


**2 - Creating a manual mean function**<br>
*Remembering how functions in python work*

In [2]:

def calculate_mean(numbers):
    # The function calculates the mean (average) of a list of numbers.
    total = 0
    print(f"starting total: {total}")
    print(f"length of numbers (number of elements in your list): {len(numbers)}")
        #len(numbers) is the number of items in the list 
        # Which is used to calculate the mean by dividing the total sum by this "length".
    for num in numbers:
        total += num
        print (f"Current total: {total}")
    return total / len(numbers)



my_numbers = [5, 7, 3, 10, 24]
print(f"Your average is: {calculate_mean(my_numbers)}")

starting total: 0
length of numbers (number of elements in your list): 5
Current total: 5
Current total: 12
Current total: 15
Current total: 25
Current total: 49
Your average is: 9.8


**3 - Using Numpy for Arrays**<br>
*Using Numpy functions to do the heavy lifting instead of making a python function*

In [ ]:
numpy_mean = np.mean(my_numbers)
print(f"Using numpy, the average is: {numpy_mean}")
#here you can see that the result from our function and the result from numpy's mean function are the same 
# ...which confirms that our function is working correctly.

#Numpy can do so much heavy lifting!


**4 - Your first Array**<br>
*Using arrays x Numpy*<br><br>

*Have a think about the differences between lists and arrays*

In [3]:
#Numpy is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing, data analysis, and machine learning due to its performance and ease of use.

#Establishing a python list and a numpy array to demonstrate the differences between them.
#python_list
python_list = [1, 2, 3, 4, 5]

#numpy_array
numpy_array = np.array([1, 2, 3, 4, 5])

#Outputting the python list and the numpy array, along with their types, to show the differences between them.
print(f"Python list: {python_list}")
print(type(python_list))
print(f"Numpy array: {numpy_array}")
print(type(numpy_array))


Python list: [1, 2, 3, 4, 5]
<class 'list'>
Numpy array: [1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#Playing around with the first element of both the python list and the numpy array to show how they can be accessed in a similar way, but they are different data structures.
print(f"First element of python list: {python_list[0]}")
print(f"First element of numpy array: {numpy_array[0]}")




First element of python list: 1
First element of numpy array: 1


In [5]:
#Now let's see how we can perform operations on both the python list and the numpy array.
print("")
print(python_list*2) # This will repeat the list, not perform element-wise multiplication
print(numpy_array*2) # This will perform element-wise multiplication, multiplying each element by 2


#adding to the python list and the numpy array to show how they can be modified.
print("")
python_list.append(6)
numpy_array = np.append(numpy_array, 6)
print(f"Modified python list: {python_list}")
print(f"Modified numpy array: {numpy_array}")
#the difference in how we modify the python list and the numpy array is evident here. We use the append method for the python list, while for the numpy array we use the np.append function, which creates a new array with the added element.



[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]

Modified python list: [1, 2, 3, 4, 5, 6]
Modified numpy array: [1 2 3 4 5 6]


In [6]:
#Now let's see how we can perform mathematical operations on both the python list and the numpy array.
for i in numpy_array:
    multiplier = 2
    i *= multiplier
    multiplier *= 2
    print(i)

2
4
6
8
10
12


In [ ]:
#Summary of lists vs numpy arrays
# 1. Lists are more flexible and can contain different data types, while numpy arrays are homogeneous and typically contain numerical data.
# 2. Numpy arrays are more efficient for numerical computations and support element-wise operations, while lists do not.
# 3. Numpy provides a wide range of mathematical functions that can be applied to arrays, while lists require manual implementation for such operations.


*Looking at some final quesitons & summing up the difference between lists and arrays*


1. Why does python_list * 2 repeat the list instead of doubling the values?
2. What does ndarray stand for in numpy.ndarray?
3. Could you rewrite calculate_mean() without a for loop, using only Python built-ins? (Hint: look up sum() and len())

In [ ]:
#python_list * 2 repeats the list instead of doubling the values because the * operator for lists in Python is defined to concatenate the list with itself a specified number of times. So, when you do python_list * 2, it creates a new list that contains the elements of python_list repeated twice, resulting in [1, 2, 3, 4, 5, 1, 2, 3, 4, 5].

In [8]:
#ndarray
#The ndarray (n-dimensional array) is the core data structure in NumPy. It is a powerful and flexible container for large datasets, allowing for efficient storage and manipulation of multi-dimensional arrays. The ndarray can hold elements of the same data type, which allows for optimized performance when performing mathematical operations.
#The ndarray supports a wide range of operations, including element-wise arithmetic, broadcasting, and various mathematical functions. It also provides methods for reshaping, slicing, and indexing arrays, making it a fundamental tool for scientific computing and data analysis in Python.
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"ndarray:\n{ndarray}")

first_ndarray_element = ndarray[1]
print(first_ndarray_element) #This will print the second row of the ndarray, which is [4, 5, 6]. In NumPy, indexing starts at 0, so ndarray[1] refers to the second row of the array.

print(ndarray.shape) #This will output the shape of the ndarray, which is (3, 3) in this case, indicating that it has 3 rows and 3 columns.
print(ndarray.shape[0]) #This will output the number of rows in the ndarray, which is 3.
print(ndarray.shape[1]) #This will output the number of columns in the ndarray, which is 3.
print(ndarray.size) #This will output the total number of elements in the ndarray, which is 9 (3 rows * 3 columns).

for i in range(ndarray.shape[0]):
    for j in range(ndarray.shape[1]):
        print(f"Element at position ({i}, {j}): {ndarray[i, j]}")



ndarray:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
(3, 3)
3
3
9
Element at position (0, 0): 1
Element at position (0, 1): 2
Element at position (0, 2): 3
Element at position (1, 0): 4
Element at position (1, 1): 5
Element at position (1, 2): 6
Element at position (2, 0): 7
Element at position (2, 1): 8
Element at position (2, 2): 9


In [9]:
# recalculating the mean using numpy's mean function to show how it can be done in a more efficient way compared to our custom function.
numpy_mean = np.mean(my_numbers)
print(f"Using numpy, the average is: {numpy_mean}")

Using numpy, the average is: 9.8


✅ Your Task for This Module
Write a script that does all of the following:

Creates a Python list of 8 numbers of your choice
Calculates the mean using your own function
Calculates the mean using NumPy
Confirms they match by printing both
Bonus: Try passing a NumPy array directly into your manual calculate_mean() function — does it still work? Why or why not?

In [11]:
myPyList = [45, 12, 6, 9, 12, 15, 18, 21, 24, 27]

#calculating the mean using my own function
def calculate_mean(myPyList):
    total = 0
    for num in myPyList:
        total += num
    return total / len(myPyList)

#calculating the mean using numpy's mean function
numpy_mean = np.mean(myPyList)
print(f"Using my function, the average is: {calculate_mean(myPyList)}")

#passing the numpy array to the calculate_mean function to show that it can work with both lists and numpy arrays, but it is not as efficient as using numpy's mean function.
print(f"Using my function with a numpy array, the average is: {calculate_mean(myPyList)}")


Using my function, the average is: 18.9
Using my function with a numpy array, the average is: 18.9
