**1 - Core Creation Basics**<br>
*Creating an array and different functions*

In [2]:
import numpy as np

In [12]:
# 1. Creating a python list manually
a = np.array([1, 2, 3, 4, 5])

# 2. All 0 - this is useful for initialising empty result arrays
b = np.zeros((3,3))
b2 = np.zeros(5) # this is a 1D array of 5 zeros

# 3. All 1 - same concept, just a different default value
c = np.ones((2,4))

# 4. Arange - this is like python's built in range function, but it returns an array instead of a list)
d = np.arange(0, 10, 2) # this is like range(0, 10, 2) - it starts at 0, goes up to (but not including) 10, and steps by 2

# 5. Linspace - N evenly spaced points between two values
e = np.linspace(0, 1, 10) #this creates an array of 10 evenly spaced points between 0 and 1

# 6. Random numbers between 0 and 1
f = np.random.rand(5) # this creates a 1D array of 5 random numbers between 0 and 1
# 6a. Random integers between a and b
f2 = np.random.randint(0, 10, (3,3)) # this creates a 3x3 array of random integers between 0 and 10 (not including 10

print("np.array:\n", a, "\n")
print("np.zeros:\n", b, "\n")
print("np.zeros:\n", b2, "\n")
print("np.ones:\n", c, "\n")
print("np.arrange:\n", d, "\n")
print("np.linspace:", e, "\n")
print("np.random.rand:\n", f, "\n")
print("np.random.randint:\n", f2, "\n")

np.array:
 [1 2 3 4 5] 

np.zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

np.zeros:
 [0. 0. 0. 0. 0.] 

np.ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

np.arrange:
 [0 2 4 6 8] 

np.linspace: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ] 

np.random.rand:
 [0.70978861 0.58035377 0.83208516 0.25531459 0.10892897] 

np.random.randint:
 [[4 1 5]
 [6 3 3]
 [0 8 2]] 



**2 - Interrogating your arrays**<br>
*Every array has attributes that can be accessed to find out more about the array. This is useful for debugging and understanding your data.*

In [ ]:
my_2darray = np.array([[1, 2, 3],[4, 5, 6]])

print("Shape: ", my_2darray.shape,"\n") #(rows, columns) !!
print("Ndim: ", my_2darray.ndim,"\n") # number of dimensions
print("Dtype: ", my_2darray.dtype,"\n") # data type of elements
print("Size: ", my_2darray.size,"\n") # total number of elements (rows * columns for 2D arrays)

#These are called attributes - not functions!! They are properties the array has, not things it does

Shape:  (2, 3) 

Ndim:  2 

Dtype:  int64 

Size:  6 



**3 - Arange vs linspace**<br>
*What are the differences between them?*

In [8]:
#Arange - you control the STEP SIZE
# "Give me a range of numbers from 0 to 10, jumping by 2"
print(np.arange(0, 10, 2)) # this is like range(0, 10, 2) - it starts at 0, goes up to (but not including) 10, and steps by 2

#Linspace - you control the NUMBER OF POINTS
# "Give me 10 evenly spaced points between 0 and 10"
print(np.linspace(0, 10, 10)) #this creates an array of 10 !!evenly!! spaced points between 0 and 10

[0 2 4 6 8]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


💡 When would you use linspace in quant work?<br>*Imagine plotting a smooth price curve or generating time intervals — you know your start, end, and how many points you want. That's linspace territory!*

**4 - Data Type (dtype)**

In [ ]:
#Integer Array
int_array = np.array([1,2,3])
print(int_array.dtype)

float_array = np.array([1.0,2.0,3.0])
print(float_array.dtype)

mixed_array = np.array([1,2.0,3])
print(mixed_array.dtype) #numpy promotes to the safer type



int64
float64
float64


This automatic promotion is called *type casting* - I.e, numpy picks the type that can safely represent all values.

✅ Your Task for This Module
Write a script that does all of the following:<br><br>

1. Create an array of even numbers from 0 to 50 using arange<br>
2. Create an array of exactly 7 evenly spaced values between 0 and 100 using linspace<br>
3. Create a 4x4 matrix of zeros — then print its shape, ndim, and size<br>
4. Create a 3x3 matrix of random numbers and print its dtype<br>
5. Bonus 🌶️: Create a 1D array of 5 ones, then see if you can figure out how to create it as floats instead of integers (hint: check the dtype parameter in np.ones)

In [16]:
# 1. Array of even numbers from 0 to 50
even_numbers = np.arange(0,51,2)
print(even_numbers)
print(even_numbers[-1],"\n")

# 2. Array of exactly 7 evenly spaced values between 0 and 100
evenly_spaced = np.linspace(0,100,7)
print(evenly_spaced,"\n")

# 3. 4x4 matrix of 0's, and their shape, ndim, and size
zeros_matrix = np.zeros((4,4))
print(zeros_matrix)
print("Shape:", zeros_matrix.shape)
print("Number of dimensions:", zeros_matrix.ndim)
print("Size:", zeros_matrix.size,"\n")

# 4. 3x3 matrix of random numbers and it's dtype
random_matrix = np.random.rand(3,3)
print(random_matrix,"\n")
print("Dtype:", random_matrix.dtype)



[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
50 

[  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.        ] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (4, 4)
Number of dimensions: 2
Size: 16 

[[0.98199367 0.7029847  0.24302459]
 [0.81596018 0.44021933 0.74643993]
 [0.70767336 0.85020621 0.67946847]] 

Dtype: float64


In [19]:
array_of_ones = np.ones((2,5),float) # this creates a 2x5 array of 1's with a float data type
print(array_of_ones)

# More explicit — what you'll see in most codebases
array_of_onesv2 = np.ones((2, 5), dtype=float)
print(array_of_onesv2)

# Most explicit of all — specifies exactly how many bits
array_of_onesv3 = np.ones((2, 5), dtype=np.float64)
print(array_of_onesv3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Re: Above All three do the same thing — but explicitly naming dtype= makes your code more readable and intentional. When someone reads dtype=np.float64 they'll know exactly what you meant

**Answering questions**

1. The key difference between arange and linspace is that with arange, you can control the steps, and with linspace, you only control the number of points...<br>
Linspace is also inclusive of the stop value where as arange is exclusive of the stop!

<br><br>

2. A 2D array of zeros can be useful in real code as it gives you a blank matrix simply, without having to create it manually each time (e.g if you're looping)<br><br> Example:<br>
results = np.zeros((10, 3))  # pre-allocate your results matrix<br>
for i in range(10):<br>
    results[i] = some_calculation()  # fill it row by row<br>

<br><br>

3. Whilst size can tell you the number of elements, shape tells you the dimensions, i.e wide and short or narrow but long.
<br> Furthermore, size gives you a single number (total elements) whereares shape gives you a tuple that tells you the size of each dimension individually...