In this module, we'll look at Indexing and slicing.<br>This is how you 'reach into' an array and pull out exactly what you want — a single value, a row, a column, or a filtered subset.

In [1]:
import numpy as np

**1 - Basic Indexing (of 1D Arrays)**

In [8]:
prices = np.array([101, 103, 99, 107, 110, 108, 115, 113, 120, 118])

#picking out single elements
print(prices[0])  # First element
print(prices[-1])  # Last element
print(prices[-2])  # Second to last element
print("")
#Slicing - picking out a range of elements. 
# The syntax is: array[start:stop:step] - note: the stop index is exclusive, meaning it is not included in the slice.
print("First five elements:\n", prices[0:5])  # First five elements
print("From the sixth element to the end:\n", prices[5:])   # From the sixth element to the end
print("First five elements (same as prices[0:5]):\n", prices[:5])   # First five elements (same as prices[0:5])
print("Every second element:\n", prices[::2])  # Every second element
print("Every second element starting from the second element:\n", prices[1::2])  # Every second element starting from the second element
print("All elements in reverse order:\n", prices[::-1])  # All elements in reverse order
print("Every second element in reverse order:", prices[::-2])  # Every second element in reverse order




101
118
120

First five elements:
 [101 103  99 107 110]
From the sixth element to the end:
 [108 115 113 120 118]
First five elements (same as prices[0:5]):
 [101 103  99 107 110]
Every second element:
 [101  99 110 115 120]
Every second element starting from the second element:
 [103 107 108 113 118]
All elements in reverse order:
 [118 120 113 115 108 110 107  99 103 101]
Every second element in reverse order: [118 113 108 107 103]


**2 - 2D Indexing (Matricies)**

In [19]:
#Imagine this as 3 stocks (rows) over 4 days (columns)
portfolio = np.array([[100, 102, 101, 105],     # Stock A
                      [200, 198, 202, 205],     # Stock B
                      [300, 305, 310, 315]])    # Stock C

# Single value - [row, column]
print(portfolio[0, 0])  # Price of Stock A (row 1) on Day 1 (column 1)
print(portfolio[2, 2])  # Price of Stock C (row 3) on Day 3 (column 3)

#Entire row - one stock's prices over all days
print(portfolio[1, :]) # Prices of Stock B (row 2) over all days
print(portfolio[2, :]) # Prices of Stock C (row 3) over all days

#Entire column - all stocks' prices on a specific day
print(portfolio[:, 2]) # Prices of all stocks on Day 3 (column 3)

#slicing - picking out a range of rows and columns
print(portfolio[0:2, 1:3])  # Prices of Stock A and Stock B (rows 1-2) on Day 2 and Day 3 (columns 2-3)
 
# : on its own means "all", so portfolio[:, 1:3] means "all rows, but only columns 1 and 2"


100
310
[200 198 202 205]
[300 305 310 315]
[101 202 310]
[[102 101]
 [198 202]]


**3 - Boolean Indexing**

In [23]:
prices = np.array([101, 103, 99, 107, 110, 108, 115, 113, 120, 118])

mask = prices > 110
print(mask)  # This will print a boolean array where True indicates the condition is met

# Now we can use this boolean array to filter the original prices array
print(prices[prices > 110])  # This will print only the prices that are greater than 110
print(prices[mask])  # This will give the same result as the previous line, using the mask variable

# Combine conditions with & (and) and | (or)
print(prices[(prices > 105) | (prices < 115)])  # between 105 and 115

[False False False False False False  True  True  True  True]
[115 113 120 118]
[115 113 120 118]
[101 103  99 107 110 108 115 113 120 118]


This is powerful because you'll be able to write returns[returns < -0.02] to instantly find all days where your portfolio dropped more than 2%. No loops needed — just one line!

**4 - np.where()‼️ **<br>
*Instead of filtering values, this functions lets you find the indicies (position of the elements/their indexes) where a condition is true*

In [82]:
indicies = np.where(prices > 110)
print(indicies)  # This will print the indices of the elements that are greater than 110
print(indicies[0])  # np.where returns a tuple, so we need to access the first element to get the array of indices

print(prices[indicies])  # This will print the values of the elements that are greater than 110 using the indices

(array([6, 7, 8, 9]),)
[6 7 8 9]
[115 113 120 118]


Think of boolean indexing as asking "give me the values", and np.where() as asking "give me the positions". Both are useful in different situations!

**5 - np.diff()**

In [28]:
prices2 = np.array([10, 8, 9, 22, 5, 4])
# Calculates difference between consecutive elements
changes = np.diff(prices2)
print(changes)  # [2, -4, 8, 3, -2, 7]

# Find days where price DROPPED
drops = np.where(np.diff(prices) < 0)
print("Price dropped on days:", drops)

[ -2   1  13 -17  -1]
Price dropped on days: (array([0, 3, 4]),)


**Task Time!!!**
<br><br>
Using the arrays below:
<br>
1. Print the last 3 prices from prices using slice notation<br>
2. Print every other price starting from the first element<br>
3. From portfolio, extract Stock C's entire price history<br>
4. From portfolio, extract all stocks' prices on Day 1 only<br>
5. Using boolean indexing, find all prices in prices that are between 100 and 110 inclusive<br>
6. Use np.where() to find the index of the maximum price in prices (hint: combine with np.max() or look up np.argmax()!)<br>
7. Bonus 🌶️: Use np.diff() on prices to find which day had the biggest single-day price jump — return both the day index and the value of the jump<br>

In [31]:
prices = np.array([101, 103, 99, 107, 110, 108, 115, 113, 120, 118])

portfolio = np.array([[101, 103, 99,  107],
                      [55,  58,  57,  60 ],
                      [200, 198, 205, 210]])

In [80]:
#Task 1: Print the last 3 prices from the prices array
print(prices[-3:])

#Task 2: Printing every other price, starting from the first element
print(prices[::2])

#Task 3: print stock C's entire price history
print(portfolio[2])

#Task 4: Extract all stocks' prices on day 1 only
print(portfolio[:,0])

#Task 5: Using boolean indexing, finding all prices in prices array that are between 100 and 110 inclusive
mask = (prices >= 100) & (prices <= 110)
print(prices[mask])

#Task 6: Using np.where() to find the index of the maximum price in prices
maxPriceIndex = np.where((prices == np.max(prices)))
print("Index of max price: ", maxPriceIndex)

        # Your version — correct! ✅
maxPriceIndex = np.where(prices == np.max(prices)) #cleaner way to find the index of the maximum price

        # The cleaner way — argmax() does exactly this in one shot!
maxPriceIndex = np.argmax(prices)


#******************#

#Looking at bonus task - using np.diff() on prices to find which day had the biggest single-day price jump
# Return both the day index and values of the jump
prices_priceJumps = np.diff(prices)

print("Price Jumps: ",prices_priceJumps)
largestPriceJump = np.max(prices_priceJumps)
print(largestPriceJump)
indexLargestPriceJump = np.where(prices_priceJumps == largestPriceJump)
print(indexLargestPriceJump[0])
print(f"The day of the largest price jump was day {indexLargestPriceJump[0]+1} (index no.{indexLargestPriceJump[0]})\nand the value of the jump was {largestPriceJump}, going from {prices[indexLargestPriceJump[0]]} to {prices[indexLargestPriceJump[0]+1]}")




[113 120 118]
[101  99 110 115 120]
[200 198 205 210]
[101  55 200]
[101 103 107 110 108]
Index of max price:  (array([8]),)
Price Jumps:  [ 2 -4  8  3 -2  7 -2  7 -2]
8
[2]
The day of the largest price jump was day [3] (index no.[2])
and the value of the jump was 8, going from [99] to [107]


*Answering some of the 'self-check' questions*<br><br>
1.What's the difference between boolean indexing and np.where()?
<br>
Boolean indexing gives you value of the element based on the condition/s where as np.where() returns the index.
<br>
<br>
2. What does portfolio[:, 2] return versus portfolio[2, :]?
<br>
portfolio[:,2] returns all rows but only the 3rd column, and portfolio[2,:] returns all columns but only for the 3rd row.
<br>
<br>
3. Why does np.diff() return an array that's one element shorter than the input?
<br>
np.diff() returns an array that's one element shorter than the input because the last value does not have a consecutive value to calculate the difference for.<br><br>
Improved answer: It's not the *last* value that has no pair — it's that `np.diff()` computes **between** elements, so for `n` elements there are always `n-1` gaps between them. Like fence posts — 10 posts, 9 gaps! 🪵<br><br>
[101, 103, 99, 107, 110]   ← 5 elements<br>
     ↕    ↕   ↕    ↕       ← 4 differences<br>
[  2,  -4,  8,   3]

Notes on variable naming convention: