In this module, we'll be looking at **Arrays Operations and Broadcasting**<br>
The core idea is simple: NumPy can perform operations on entire arrays without a single loop.

**1 - Element-wise operations**<br>
NumPy applies operations to every element simultaneously.

In [1]:
import numpy as np

In [2]:
prices = np.array([100, 105, 102, 110, 108])

In [6]:
#These are normal python operations that you can do. The key thing is that they are elementwise. So the operation is applied to each element of the array!
#Thus, no looops!

print(prices) #original array
print("Add 10 to each element:\n", prices + 10) #add 10 to each element
print("Subtract 5 from each element:\n", prices - 5) #subtract 5 from each element
print("Multiply each element by 2:\n", prices * 2) #multiply each element by 2
print("Divide each element by 2:\n", prices / 2) #divide each element by 2
print("Square each element:\n", prices ** 2) #square each element
print("Modulo each element by 3:\n", prices % 3) #modulo each element by 3


[100 105 102 110 108]
Add 10 to each element:
 [110 115 112 120 118]
Subtract 5 from each element:
 [ 95 100  97 105 103]
Multiply each element by 2:
 [200 210 204 220 216]
Divide each element by 2:
 [50.  52.5 51.  55.  54. ]
Square each element:
 [10000 11025 10404 12100 11664]
Modulo each element by 3:
 [1 0 0 2 0]


You can see that under the hood, NumPy is looping BUT it's doing it in C (not python!) Hence why it is faster by orders of magnitude.

**2 - Operations between two arrays**<br>
You can also do these operations BETWEEN two arrays

In [ ]:
asset_a = np.array([100, 105, 102, 110, 108])
asset_b = np.array([50,  52,  49,  55,  53 ])

#You can also do operations between arrays. The key thing is that the arrays need to be of the same shape (or compatible shapes, which we will see later). The operation is applied elementwise between the two arrays!
spread = asset_a - asset_b
print("Spread between asset_a and asset_b:\n", spread) #spread between assets, the difference at each point in time

combined = asset_a + asset_b
print("Combined value of asset_a and asset_b:\n", combined) #combined value of assets, the sum at each point in time

ratio = asset_a / asset_b 
print("Ratio of asset_a and asset_b:\n", ratio) #ratio of the two assets, the ratio at each point in time

#You can also do this between multiple arrays, e.g 3
asset_c = np.array([5, 24, 36, 36, 63])

combined2 = asset_a + asset_b + asset_c
print("Combined value of asset_a, asset_b, asset_c:\n", combined2)



Spread between asset_a and asset_b:
 [50 53 53 55 55]
Combined value of asset_a and asset_b:
 [150 157 151 165 161]
Ratio of asset_a and asset_b:
 [2.         2.01923077 2.08163265 2.         2.03773585]
Combined value of asset_a, asset_b, asset_c:
 [155 181 187 201 224]


In [17]:
#You can see here that if they are different shapes, it doesn't work
asset_a2 = np.array([100, 105, 102, 110, 108])
asset_b2 = np.array([[50,  52,  49,  55,  53 ],[5, 24, 36, 36, 63]])
asset_b3 = np.array([[50,  52,  49,  55,  53, 65, 85, 29],[5, 24, 36, 36, 63, 5, 85, 29 ]])

diff_shapes = asset_a2 + asset_b2
print(diff_shapes) # it accepts same shape but but different size

diff_shapes3 = asset_a2 + asset_b3
print(diff_shapes3) # this one should not work!


[[150 157 151 165 161]
 [105 129 138 146 171]]


ValueError: operands could not be broadcast together with shapes (5,) (2,8) 

**3 - Calculating Returns**<br>
*Here is a practical example of this ability in practise*

In [21]:
prices3 = np.array([100, 105, 102, 110, 108])

#Absolute daily change
daily_change = np.diff(prices3) #getting the difference between prices
print("Daily change:", daily_change)

# Daily return - this is a standard formula !
# (today - yesterday) / yesterday * 100
daily_returns = daily_change / prices3[:-1] * 100 # we use prices3[:-1] to get all elements except the last one, which corresponds to yesterday's price
print("Daily returns (%):", daily_returns)

Daily change: [ 5 -3  8 -2]
Daily returns (%): [ 5.         -2.85714286  7.84313725 -1.81818182]


**4 - Broadcasting**<br>
*THIS is the ability to work on **different** shapes*

In [22]:
#simple broadcasting - scalar and array
a = np.array([1,2,3,4,5])
print(a +10) # add 10 to each element of the array
# 10 is 'broadcasted' to each element of the array, so it is like doing a + 10 for each element of a

#2D broadcasting - this is way more powerful and is the basis of many operations in numpy. The key thing is that the shapes of the arrays need to be compatible. The operation is applied elementwise between the two arrays, but numpy will automatically 'broadcast' the smaller array to match the shape of the larger array.
portfolio = np.array([[100, 105, 102],   # Stock A
                      [50,  52,  49 ],   # Stock B
                      [200, 198, 205]])  # Stock C

#Multiply each stock by a different weight (in one line...)
weights = np.array([0.5, 0.3, 0.2])
weighted_potfolio = portfolio * weights[:, np.newaxis] # we use np.newaxis to add a new axis to the weights array, so it becomes a column vector and can be broadcasted to match the shape of the portfolio array
print(weighted_potfolio) # this gives us the weighted portfolio, where each stock is multiplied by its corresponding weight

[11 12 13 14 15]
[[50.  52.5 51. ]
 [15.  15.6 14.7]
 [40.  39.6 41. ]]


np.newaxis reshapes weights from shape (3,) to (3,1) so it broadcasts correctly across columns.

remember: (row, column)

so it effectly turns into:

[0.5, 0.5, 0.5],   
[0.3, 0.3, 0.3],   
[0.2, 0.2, 0.2]

**5 - Aggregations Across Axis<br>**
*With 2D arrays you can choose to aggregate across rows or columns*

In [ ]:
portfolio = np.array([[100, 105, 102, 110],   # Stock A — 4 days
                      [50,  52,  49,  55 ],   # Stock B
                      [200, 198, 205, 210]])  # Stock C

print(np.mean(portfolio))           # mean of ALL values
print(np.mean(portfolio, axis=0))   # mean of each DAY (across stocks)
    # i.e, we are taking the mean for each column (day)
print(np.mean(portfolio, axis=1))   # mean of each STOCK (across days)
    # i.e, we are taking the mean for each row (stock)

119.66666666666667
[116.66666667 118.33333333 118.66666667 125.        ]
[104.25  51.5  203.25]


Axis 0 = down the rows, Axis 1 = across the columns. 
Remember "axis 0 collapses rows, axis 1 collapses columns"

portfolio = [[100, 105, 102, 110],   ← row 0 (Stock A)
             [50,  52,  49,  55 ],   ← row 1 (Stock B)
             [200, 198, 205, 210]]   ← row 2 (Stock C)
               ↑    ↑    ↑    ↑
              col0 col1 col2 col3
             Day1 Day2 Day3 Day4
            
axis=0 means "travel downward ↓ through rows"
axis=1 means "travel sideways → through columns"

np.mean(portfolio, axis=0)  # collapse the ROWS — one answer per COLUMN
# → "what's the average price on each day?"
# → shape goes from (3,4) to (4,)

np.mean(portfolio, axis=1)  # collapse the COLUMNS — one answer per ROW
# → "what's the average price of each stock?"
# → shape goes from (3,4) to (3,)
```

---

## The Practical Way 🏦

Just ask yourself:
> *"What do I want ONE answer per ___?"*
```
One answer per STOCK?  → axis=1  (collapse across days)
One answer per DAY?    → axis=0  (collapse across stocks)



In [55]:
pythonportfolio = np.array([[100, 105, 102, 110],
                            [50,  52,  49,  55 ],
                            [200, 198, 205, 210]])

print("No axis — one number for everything:")
print(np.mean(portfolio))           # 118.08...

print("\naxis=0 — one number PER COLUMN (per day):")
print(np.mean(portfolio, axis=0))   # [116.67, 118.33, 118.67, 125]

print("\naxis=1 — one number PER ROW (per stock):")
print(np.mean(portfolio, axis=1))   # [104.25, 51.5, 203.25]

#  check — does axis=1 give you 3 numbers (one per stock)? Does axis=0 give you 4 numbers (one per day)?

No axis — one number for everything:
119.66666666666667

axis=0 — one number PER COLUMN (per day):
[116.66666667 118.33333333 118.66666667 125.        ]

axis=1 — one number PER ROW (per stock):
[104.25  51.5  203.25]


**Task Time**<br>
1. Calculate the **daily percentage returns** for `prices_a`
2. Calculate the **spread** between `prices_a` and `prices_b` at each point
3. Find the **mean, max, and min** of the spread
4. Using `portfolio`, find the **mean price of each stock** across all 4 days (hint: think about which axis!)
5. Using `portfolio`, find the **highest price on each day** across all stocks
6. **Bonus 🌶️:** Normalise `prices_a` so that all values are between 0 and 1. The formula is:
```
normalised = (x - min) / (max - min)


In [43]:
prices_a = np.array([100, 105, 102, 110, 108, 115])
prices_b = np.array([80,  83,  79,  85,  82,  88 ])

portfolio = np.array([[100, 105, 102, 110],
                      [50,  52,  49,  55 ],
                      [200, 198, 205, 210]])

In [56]:
# 1. Calculate daily returns
daily_returns_a = np.diff(prices_a) / prices_a[:-1] * 100
print("Daily returns for asset A (%):\n", daily_returns_a, "\n")


# 2. Calculate the spread between the two assets
spread = prices_a - prices_b
print("Spread between asset A and asset B:\n", spread, "\n")

# 3. Calculting max, max, min of the spread
print("Max spread:", np.max(spread))
print("Min spread:", np.min(spread))
print("Mean spread:", np.mean(spread), "\n")

# 4. Using portfolio array, finding the mean price of each stock across the 4 days
print(np.mean(portfolio, axis=1))

# 5. Finding the highest price on each day, across all stocks
print(np.max(portfolio, axis=0))

print("")

# Bonus: Normalising price_a so all the values are between 0 and 1
#normalised = (x - min) / (max - min)

# (x - min)
print(np.min(prices_a)) # min
print(np.max(prices_a, )) # mx

prices_a_normalised = ( prices_a - np.min(prices_a) ) / ( np.max(prices_a) - np.min(prices_a) )
print(prices_a_normalised)
print(np.round(prices_a_normalised,4))





Daily returns for asset A (%):
 [ 5.         -2.85714286  7.84313725 -1.81818182  6.48148148] 

Spread between asset A and asset B:
 [20 22 23 25 26 27] 

Max spread: 27
Min spread: 20
Mean spread: 23.833333333333332 

[104.25  51.5  203.25]
[200 198 205 210]

100
115
[0.         0.33333333 0.13333333 0.66666667 0.53333333 1.        ]
[0.     0.3333 0.1333 0.6667 0.5333 1.    ]


In [60]:
prices = np.array([100, 105, 102, 110])
returns = np.diff(prices) / prices[1:]

print(returns)
print(np.diff(prices))
print(prices[1:])

[ 0.04761905 -0.02941176  0.07272727]
[ 5 -3  8]
[105 102 110]


In [61]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
print(a * b)
# THis is Hadamard Product!

[ 1  4  9 16 25]
