**Why does this matter in Quant Finance?**

Imagine you have a (252, 4) matrix of daily returns for 4 stocks, and you want to subtract each stock's mean return from every single day. The naive approach is a loop — iterating over 252 rows one by one. Broadcasting lets NumPy do it in one line, no loop, running at C speed under the hood.

This is the difference between a backtest that runs in 0.2 seconds vs 20 seconds on real data. At scale, it's not even close. 🚀    

**Part 1 - Vectorisation**

Vectorisation means applying an operation to an entire array at once rather than element by element in a Python loop

In [ ]:
import numpy as np

In [ ]:
returns = np.array([0.01, -0.02, 0.015, -0.03, 0.025])

# Non-vectorised — slow Python loop
result = []
for r in returns:
    result.append(r * 100)

# Vectorised — fast, clean, Pythonic
result = returns * 100

#Under the hood, NumPy pushes that operation down into compiled C code — orders of magnitude faster than a Python loop.


**Part 2 - Broadcasting**

Broadcasting is Numpy's ruleset for how to handle operations between arrays of different shapes - without copying data or writing loop. This is like how we covered in module 4.

In [ ]:
#A simple example of scalar broadcasting is multiplying an array by a single number. The number is "stretched" across all elements of the array, and the operation is applied element-wise.

returns = np.array([0.01, -0.02, 0.03, -0.01, 0.02])

# Scalar broadcast — the 100 is "stretched" across all elements
returns * 100
# [ 1.  -2.   3.  -1.   2.]

In [ ]:
# 3 days × 4 stocks return matrix
returns = np.array([[ 0.01, -0.02,  0.03,  0.00],
                    [-0.01,  0.02, -0.01,  0.03],
                    [ 0.02,  0.01,  0.00, -0.02]])
# shape: (3, 4)

# Mean return per stock (one value per column)
mean_returns = np.array([0.01, 0.00, 0.01, 0.00])
# shape: (4,)

# Subtract mean from every day — broadcasting handles the shape mismatch!
excess_returns = returns - mean_returns
print(excess_returns)
# [[ 0.    -0.02   0.02   0.  ]
#  [-0.02   0.02  -0.02   0.03]
#  [ 0.01   0.01  -0.01  -0.02]]
